### ISSUE TITLE
Repeating records

### ISSUE THREAD

**Issue by mattmcneeney** [openactive/realtime-paged-data-exchange#26]
A common use case for physical data is for sessions/activities/classes to repeat on a daily, weekly or another periodic basis. These sessions often share lots of similar data (information, location, pricing, etc) and differ only by start and end times. How can the proposed standard be improved to handle this? This could have a significant impact on reducing load, allowing the endpoints to be polled more frequently.

Re: [4.2 Core concept](https://www.openactive.io/realtime-paged-data-exchange/#core-concept)

**Comment by rujenner** [comment]
This is something that we (Playwaze) are looking at just now. We have two types of activity that we want to publish:
1. Courses - could be just one activity (one day) or could be multiple (different days, times) e.g. a course consists of 9 - 10am on Friday and Saturday, and all day Sunday.
2. Sessions - generally a repeating sequence of activities running weekly, monthly etc. Although sessions can also be ad hoc e.g. random bike rides organised by a cycling club. We accommodate both.

From a participants perspective joining these are quite different:
1. Joining a course is a single join event. Regardless of how many activities (days) are in the course you either join them all or none at all. This is an "absolute join" - you click a book button and you are participating.
2. Joining sessions is a repeating event. In Playwaze you sign up to be a potential participant of the sessions. Only after joining (potentially through an OA interface) will you then make the decision to join in each session (which would be done directly through the source app - in our case, Playwaze). I might not play this week, but I'll play next week. So in this case it is not an "absolute join". You are simply saying "I'd like to be included, but I'll decide on my participation later"

With this in mind we would want to publish the parent data object i.e. the course or the sessions header. However, now there is another question. Sometimes sessions and courses have fixtures within them that have different locations, different start times etc. What the recipient would probably want to see is something like: Course name, location, dates, start times, end times, price etc. We already aggregate this in Playwaze - if they are all the same we display the values, if they vary we display "variable locations" or "variable start times". This is OK in Playwaze as the user can click on the course to see all the fixtures for clarification. However, through an OA interface they wouldn't be able to do this.

Perhaps, rather than courses and sessions always returning all their fixtures (as we are doing at the moment through our endpoint) we should have an option to just return top level data which includes data on the course (name, organiser, price etc) along with aggregated summary data on the fixtures within it.

**Comment by nickevansuk** [comment]
This is now covered within the [modelling specification](https://www.openactive.io/modelling-opportunity-data/) (Schedule / recurrence rules) and also within the [RPDE spec](https://www.openactive.io/realtime-paged-data-exchange/#related-entities) (related entities).

See https://github.com/openactive/activation/issues/6#issuecomment-312423917 for an example. More complete examples to come.
