### ISSUE TITLE
Allow for removing historic data with a retention period

### ISSUE THREAD

**Issue by lukehesluke** [openactive/realtime-paged-data-exchange#94]
May the Realtime Paged Data Exchange standard last for 100 years!

Even in the few years it has existed so far since 2015, some implementers have racked up a lot of sessions and a LOT of slots that are exposed in an RPDE feed.

RPDE specifies that:

> If any record is added to the list or updated it must remain in the list in perpetuity while it is in an "updated" state, or remain in the list for at least 7 days from the point in time at which it transitioned to a "deleted" state

(Section 4.1, https://www.openactive.io/realtime-paged-data-exchange/#core-concept)

This implies that an implementation cannot ever remove historic items from the feed.

This means that the feed could start with hundreds of pages before an RPDE client finally gets to present day data. Additionally, it means that an RPDE implementer needs to retain historic data in perpetuity. This would become cumbersome. It's best to keep databases as lean as possible for performance, cost and stability reasons.

**Comment by nickevansuk** [comment]
Great point @lukehesluke - this is perhaps something that we should add to implementation guidance rather than a change to the spec itself.

We've updated the guidance here to reflect current practice: https://developer.openactive.io/publishing-data/data-feeds/scaling-feeds#retention-period

Let me know if that helps or if there's anything we can clarify further?

**Comment by lukehesluke** [comment]
Thanks @nickevansuk this solves it and aligns the historic retention policy with the RPDE spec line about `updated` items remaining in the list in perpetuity :+1:
